# Generated by Django 3.2.9 on 2021-11-09 18:08

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', wagtail.core.fields.RichTextField(max_length=100, verbose_name='Адрес предприятия')),
                ('telephones', wagtail.core.fields.RichTextField(max_length=100, verbose_name='Телефоны предприятия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email предприятия')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футеры',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephones', wagtail.core.fields.RichTextField(max_length=100, verbose_name='Телефоны предприятия')),
                ('address', wagtail.core.fields.RichTextField(max_length=100, verbose_name='Адрес предприятия')),
            ],
            options={
                'verbose_name': 'Хедер',
                'verbose_name_plural': 'Хедеры',
            },
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_product', wagtail.core.fields.StreamField([('product_card_block', wagtail.core.blocks.StructBlock([('img_card_product', wagtail.images.blocks.ImageChooserBlock(help_text='Загрузите изображение', label='Изображение продукции')), ('name_card_product', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Введите название продукции', label='Наименование продукции')), ('description_card_product', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Введите описание продукции', label='Описание продукции'))]))], blank=True, verbose_name='Карточка продукции')),
            ],
            options={
                'verbose_name': 'Карточка продукции',
                'verbose_name_plural': 'Карточки продукции',
            },
        ),
    ]
