# Generated by Django 3.2.9 on 2021-11-10 06:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_footer_header_productcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='card_product',
            field=wagtail.core.fields.StreamField([('product_card_block', wagtail.core.blocks.StructBlock([('img_card_product', wagtail.images.blocks.ImageChooserBlock(help_text='Загрузите изображение', label='Изображение продукции')), ('name_card_product', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Введите название продукции', label='Наименование продукции')), ('description_card_product', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Введите описание продукции', label='Описание продукции'))]))], blank=True, verbose_name='Карточки продукции'),
        ),
    ]
