# Generated by Django 3.2.9 on 2021-11-10 06:29

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211110_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='productcard',
            name='id',
            field=models.AutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcard',
            name='card_product',
            field=wagtail.core.fields.StreamField([('product_card_block', wagtail.core.blocks.StructBlock([('img_card_product', wagtail.images.blocks.ImageChooserBlock(help_text='Загрузите изображение', label='Изображение продукции')), ('name_card_product', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Введите название продукции', label='Наименование продукции')), ('description_card_product', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Введите описание продукции', label='Описание продукции'))]))], blank=True, verbose_name='Карточки продукции'),
        ),
    ]
