# Generated by Django 3.2.9 on 2021-11-10 08:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_eventnewspages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnewspages',
            name='events_news',
            field=wagtail.core.fields.StreamField([('events_block', wagtail.core.blocks.StructBlock([('event_data', wagtail.core.blocks.CharBlock(max_length=2, verbose_name='Число месяца')), ('event_month', wagtail.core.blocks.CharBlock(max_length=8, verbose_name='Месяц')), ('event_name', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'enter'], max_length=200, null=True, verbose_name='Название мероприятия')), ('event_description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'enter'], null=True, verbose_name='Описание мероприятия'))])), ('news_block', wagtail.core.blocks.StructBlock([('news_data', wagtail.core.blocks.CharBlock(max_length=2, verbose_name='Число месяца')), ('news_month', wagtail.core.blocks.CharBlock(max_length=8, verbose_name='Месяц')), ('news_name', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'enter'], max_length=200, null=True, verbose_name='Название новости')), ('news_description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'enter'], null=True, verbose_name='Описание новости'))]))], blank=True, verbose_name='Мероприятия и новости'),
        ),
    ]
