# Generated by Django 3.2.9 on 2021-11-10 08:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_eventnewspages_events_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnewspages',
            name='events_news',
            field=wagtail.core.fields.StreamField([('events_block', wagtail.core.blocks.StructBlock([('event_data', wagtail.core.blocks.CharBlock(label='Число месяца', max_length=2)), ('event_month', wagtail.core.blocks.CharBlock(label='Месяц', max_length=8)), ('event_name', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'enter'], help_text='Введите название мероприятия', label='Название мероприятия', max_length=200, null=True)), ('event_description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link', 'enter'], help_text='Введите описание мероприятия', label='Описание мероприятия', null=True))]))], blank=True, verbose_name='Мероприятия и новости'),
        ),
    ]
