# Generated by Django 3.2.9 on 2021-11-10 09:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211110_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('events_news', wagtail.core.blocks.StructBlock([])), ('products', wagtail.core.blocks.StructBlock([]))], blank=True),
        ),
    ]
