# Generated by Django 3.2.9 on 2021-11-10 10:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('events_news', wagtail.core.blocks.StructBlock([])), ('products', wagtail.core.blocks.StructBlock([])), ('slideshow', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Картинка')), ('caption', wagtail.core.blocks.CharBlock(label='Название картинки')), ('description', wagtail.core.blocks.CharBlock(label='Описание картинки'))])))], blank=True),
        ),
    ]
