# Generated by Django 3.2.9 on 2021-11-11 07:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(help_text='Введите название страницы', label='Название страницы')), ('heading', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'hr', 'bold', 'italic'], help_text='Введите название заголовка', label='Заголовок №1')), ('caption', wagtail.core.blocks.RichTextBlock(features=['h4', 'h5', 'h6', 'hr', 'bold', 'italic'], help_text='Введите название заголовка', label='Заголовок №2')), ('events_news', wagtail.core.blocks.StructBlock([])), ('products', wagtail.core.blocks.StructBlock([])), ('slideshow', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Картинка')), ('caption', wagtail.core.blocks.RichTextBlock(blank=True, label='Название картинки')), ('description', wagtail.core.blocks.RichTextBlock(blank=True, label='Описание картинки'))]))), ('article', wagtail.core.blocks.StructBlock([('figure_first', wagtail.images.blocks.ImageChooserBlock(label='Картинка слева')), ('description', wagtail.core.blocks.RichTextBlock(label='Статья (текст справа)'))])), ('article_two', wagtail.core.blocks.StructBlock([('figure_second', wagtail.images.blocks.ImageChooserBlock(label='Картинка справа')), ('description_second', wagtail.core.blocks.RichTextBlock(label='Статья (текст слева)'))])), ('article_product', wagtail.core.blocks.StructBlock([('image_product', wagtail.images.blocks.ImageChooserBlock(label='Картинка слева')), ('description_product', wagtail.core.blocks.RichTextBlock(label='Статья (текст справа)'))])), ('article_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'enter'], help_text='Введите текст статьи', icon='form', label='Текстовый блок')), ('photo_gallery', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Картинка'))])))], blank=True),
        ),
    ]
